import Head from 'next/head';
import styles from '../styles/About.module.scss';

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About | aya_se</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About</h1>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>氏名 &rarr;</h2>
            <p>服部 翔 (Kakeru Hattori)</p>
          </div>
          <div className={styles.card}>
            <h2>生年月日 &rarr;</h2>
            <p>2000年7月29日</p>
          </div>
          <div className={styles.card}>
            <h2>学校 &rarr;</h2>
            <p>東京工業大学 情報理工学院 情報工学系</p>
          </div>
          <div className={styles.card}>
            <h2>研究室 &rarr;</h2>
            <p>岡崎研究室, 自然言語処理</p>
          </div>
          <div className={styles.card}>
            <h2>趣味 &rarr;</h2>
            <p>DTM, 競技プログラミング, ウマ娘, Minecraft, Youtube, スキー, 御朱印 etc.</p>
          </div>
          <div className={styles.card}>
            <h2>興味・関心 &rarr;</h2>
            <p>機械学習, 自然言語処理, アルゴリズム etc.</p>
          </div>
          <div className={styles.card}>
            <h2>資格 &rarr;</h2>
            <p>英検2級, 基本情報技術者, G検定, PAST上級, TOEIC(665)</p>
          </div>
        </div>
      </main>
    </div>
  );
}
