import Head from 'next/head';
import styles from '../styles/Account.module.scss';

export default function Account() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Account | aya_se</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>History</h1>
        <div>ここはアカウントページです。</div>
      </main>
    </div>
  );
}
